#
#
# computeValueOfSpinoutsAndEntrants.R
#
#
#  Here I compute the total first funding value of spinouts and entrants
#
#----------------------------------------#


rm(list = ls())

firstFundings <- fread("data/VentureSource/firstFundingEvents.csv")[ , .(EntityID,discountedFFValue,foundingYear)]
parentsSpinouts <- fread("data/parentsSpinouts.csv")

# Only take one record pe r EntityID - just need to be able to flag that
# it is a spinout in the later calculations
parentsSpinouts <- unique(parentsSpinouts, by = "EntityID")[, .(gvkey,EntityID)]
#temp <- unique(temp, by = "EntityID")

# Merge funding information with parent firm - spinout link
setkey(firstFundings,EntityID)
setkey(parentsSpinouts,EntityID)
parentsSpinoutsFF <- parentsSpinouts[firstFundings]

parentsSpinoutsFF <- parentsSpinoutsFF[!is.na(foundingYear)]

# Label spinouts and non-spinouts
parentsSpinoutsFF[!is.na(gvkey) , isSpinout := 1]
parentsSpinoutsFF[is.na(isSpinout), isSpinout := 0]

# Replace NA values with zero
parentsSpinoutsFF[ is.na(discountedFFValue), discountedFFValue := 0]

## Compute first funding value of spinouts vs regular entrants

year_spinoutsEntrantsFFValue <- parentsSpinoutsFF[ , sum(discountedFFValue), by = c("foundingYear","isSpinout")]

year_spinoutsEntrantsFFValue <- year_spinoutsEntrantsFFValue[order(foundingYear,isSpinout)]

## Make a plot

library(ggplot2)

year_spinoutsEntrantsFFValue[ isSpinout == 1, type := "Spinout"]
year_spinoutsEntrantsFFValue[ isSpinout == 0, type := "Non-spinout"]

ggplot(data = year_spinoutsEntrantsFFValue, aes(x = foundingYear, y = V1, group = type, color = type)) + 
  geom_line() +
  theme(text = element_text(size=16)) +
  #theme(legend.position = "none") +
  ggtitle("Valuation of spinouts and non-spinouts") +
  #ggtitle("Unadjusted") + 
  xlim(1986,2009) + 
  ylab("Valuation (millions $)") +
  xlab("Year")

ggsave("../figures/spinouts_entrants_DFFV.png", plot = last_plot())

year_spinoutsEntrantsCounts <- parentsSpinoutsFF[ , .N, by = c("foundingYear","isSpinout")]
year_spinoutsEntrantsCounts[ isSpinout == 1, type := "Spinout"]
year_spinoutsEntrantsCounts[ isSpinout == 0, type := "NonSpinout"]

ggplot(data = year_spinoutsEntrantsCounts, aes(x = foundingYear, y = N, group = type, color = type)) + 
  geom_line() +
  theme(text = element_text(size=16)) +
  #theme(legend.position = "none") +
  ggtitle("Number of spinouts and non-spinouts") +
  #ggtitle("Unadjusted") + 
  xlim(1986,2009) + 
  ylab("Number of firms") +
  xlab("Year")

ggsave("../figures/spinouts_entrants_counts.png", plot = last_plot())

setkey(year_spinoutsEntrantsFFValue,foundingYear,isSpinout)
setkey(year_spinoutsEntrantsCounts,foundingYear,isSpinout)

year_spinoutsEntrantsFFValueAndCounts <- year_spinoutsEntrantsFFValue[year_spinoutsEntrantsCounts]

year_spinoutsEntrantsCounts <- dcast(year_spinoutsEntrantsFFValueAndCounts, foundingYear ~ isSpinout, value.var = "N")
year_spinoutsEntrantsFFValue <- dcast(year_spinoutsEntrantsFFValueAndCounts, foundingYear ~ isSpinout, value.var = "V1")

setnames(year_spinoutsEntrantsCounts,"0","nonSpinout")
setnames(year_spinoutsEntrantsCounts,"1","Spinout")

setnames(year_spinoutsEntrantsFFValue,"0","nonSpinout")
setnames(year_spinoutsEntrantsFFValue,"1","Spinout")

year_spinoutsEntrantsCounts[ , countRatio := Spinout / nonSpinout]
year_spinoutsEntrantsFFValue[ , FFValueRatio := Spinout / nonSpinout]


# Compute ratio of spinouts to non-spinouts in sample

spinoutsNonSpinoutsRatio <- year_spinoutsEntrantsCounts[foundingYear >= 1986 & foundingYear <= 2009][ , sum(Spinout) / sum(nonSpinout)]
spinoutsNonSpinoutDFFVsRatio <- year_spinoutsEntrantsFFValue[foundingYear >= 1986 & foundingYear <= 2009][ , sum(Spinout) / sum(nonSpinout)]

setkey(year_spinoutsEntrantsCounts,foundingYear)
setkey(year_spinoutsEntrantsFFValue,foundingYear)

out <- year_spinoutsEntrantsCounts[ , .(foundingYear,countRatio)][year_spinoutsEntrantsFFValue[, .(foundingYear,FFValueRatio)]]

## Compute avearage ratios of spinouts to non-spinouts

averageCountRatio <- out[ foundingYear >= 1986 & foundingYear <= 2009, mean(na.omit(countRatio))]
averageFFValueRatio <- out[ foundingYear >= 1986 & foundingYear <= 2009, mean(na.omit(FFValueRatio))]

out <- melt(out, id.vars = c("foundingYear"), measure.vars = c("countRatio","FFValueRatio"))

ggplot(data = out, aes(x = foundingYear, y = value, group = variable, color = as.factor(variable))) + 
  geom_line() +
  theme(text = element_text(size=16)) +
  #theme(legend.position = "none") +
  ggtitle("Ratio of spinouts to non-spinouts") +
  #ggtitle("Unadjusted") +
  xlim(1986,2009) + 
  ylim(0,2) + 
  ylab("Ratio (FFValue or Counts)") +
  xlab("Year")

ggsave("../figures/spinouts_entrants_ratio.png")

# Compute spinouts generated by R&D according to fixed effect regression results

compustat <- fread("raw/compustat/compustat_annual.csv")
compustat <- compustat[indfmt=="INDL" & datafmt=="STD" & popsrc=="D" & consol=="C"]
compustat <- compustat[ , .(gvkey,fyear,datadate,state,xrd,emp,revt,intan,act,sic,naics)]
compustat <- compustat[!is.na(fyear)]

compustat[ is.na(xrd), xrd := 0]
xrdGeneratedSpinouts <- compustat[ , .(xrd = sum(xrd)), by = "fyear"]

xrdPriceIndex <- fread("raw/rdPriceIndex.csv")
xrdPriceIndex[ , year := year(ymd(DATE))]
xrdPriceAnnual <- xrdPriceIndex[ , .(priceIndex = mean(priceIndex)), by = year]
xrdPriceAnnual[ , xrdInflation := priceIndex / priceIndex[year == 2012]]
xrdPriceAnnual[ , priceIndex := NULL]
setkey(xrdPriceAnnual,year)
setkey(xrdGeneratedSpinouts,fyear)
xrdGeneratedSpinouts <- xrdPriceAnnual[xrdGeneratedSpinouts]
xrdGeneratedSpinouts[ , xrd := xrd / xrdInflation]

productivityGrowth <- fread("raw/productivityGrowth.csv")
productivityGrowth[ , Growth := 1 + Annual/100]
productivityGrowth[ , Annual := NULL]
productivityGrowth[ , cumGrowth := cumprod(Growth)]
productivityGrowth[ , growthFactor := cumGrowth / cumGrowth[Year == 2012]]
setkey(productivityGrowth,Year)
xrdGeneratedSpinouts <- productivityGrowth[xrdGeneratedSpinouts]
xrdGeneratedSpinouts[ , xrd := xrd / growthFactor ]


cpi <- fread("raw/cpi.csv")
setnames(cpi,"Year","year")
cpi[ , cpiInflation := Annual / Annual[year == 2012]]
cpi[ , Annual := NULL]
setkey(cpi,year)
year_spinoutsEntrantsFFValue <- cpi[year_spinoutsEntrantsFFValue]

year_spinoutsEntrantsFFValue[ , `:=` (nonSpinout = nonSpinout / cpiInflation, Spinout = Spinout / cpiInflation)]


# For now hard coded from OLS regression results

xrdGeneratedSpinouts[ , spinoutsGenerated := 0.0002155 * xrd]
xrdGeneratedSpinouts[ , spinoutsGenerated_low := (0.0002155 + 0.000083) * xrd]
xrdGeneratedSpinouts[ , spinoutsGenerated_high := (0.0002155 - 0.000083) * xrd]
xrdGeneratedSpinouts[ , spinoutsFFValueGenerated := 0.00944 * xrd]
xrdGeneratedSpinouts[ , spinoutsFFValueGenerated_low := (0.00944 + 0.00303) * xrd]
xrdGeneratedSpinouts[ , spinoutsFFValueGenerated_high := (0.00944 - 0.00303) * xrd]

setkey(xrdGeneratedSpinouts,Year)



###  Construct graph showing fraction of spnouts due to R&D suggested by the micro estimates

setkey(year_spinoutsEntrantsCounts,foundingYear)

countsComparison <- xrdGeneratedSpinouts[year_spinoutsEntrantsCounts][ , .(Year,spinoutsGenerated,spinoutsGenerated_low, spinoutsGenerated_high,Spinout)]
FFValueComparison <- xrdGeneratedSpinouts[year_spinoutsEntrantsFFValue][ , .(Year,spinoutsFFValueGenerated,spinoutsFFValueGenerated_low,spinoutsFFValueGenerated_high,Spinout)]

## Compute statistics for calibration

rd_averageCountRatio <- countsComparison[ Year >= 1986 & Year <= 2009 , mean(na.omit(spinoutsGenerated / Spinout))]
rd_ratioAverageCounts <- countsComparison[ Year >= 1986 & Year <= 2009 , sum(spinoutsGenerated) / sum(Spinout)]

rd_averageValueRatio <- FFValueComparison[ Year >= 1986 & Year <= 2009, mean(na.omit(spinoutsFFValueGenerated / Spinout))]
rd_ratioAverageValues <- FFValueComparison[ Year >= 1986 & Year <= 2009, sum(spinoutsFFValueGenerated) / sum(Spinout)]


# Reshape wide to long for plotting with ggplot

setnames(countsComparison,"Spinout","allSpinoutsCount")
setnames(FFValueComparison,"Spinout","allSpinoutsFFValue")

countsComparison <- melt(countsComparison, id.vars = "Year", measure.vars = c("spinoutsGenerated","spinoutsGenerated_low","spinoutsGenerated_high","allSpinoutsCount"))
FFValueComparison <- melt(FFValueComparison, id.vars = "Year", measure.vars = c("spinoutsFFValueGenerated","spinoutsFFValueGenerated_low","spinoutsFFValueGenerated_high","allSpinoutsFFValue"))

## Make plotss

ggplot(data = FFValueComparison, aes(x = Year, y = value, group = variable, color = variable)) + 
  geom_line() +
  theme(text = element_text(size=14)) +
  #theme(legend.position = "none") +
  ggtitle("Valuation of spinouts: generated by R&D and total") +
  #ggtitle("Unadjusted") + 
  xlim(1986,2009) + 
  ylab("Valuation (millions $)") +
  xlab("Year")

ggsave("../figures/DFFVComparison.png", plot = last_plot())
  
ggplot(data = countsComparison, aes(x = Year, y = value, group = variable, color = variable)) + 
  geom_line() +
  theme(text = element_text(size=14)) +
  #theme(legend.position = "none") +
  ggtitle("Number of spinouts: generated by R&D and total") +
  #ggtitle("Unadjusted") + 
  xlim(1986,2009) + 
  ylab("# of Spinouts") +
  xlab("Year")

  ggsave("../figures/countsComparison.png", plot = last_plot())
  
  
  
### Compute relative outcomes of spinouts and entrants

# Load weighted histogram function from Weights package
  
rm(list = ls())  

wtd.hist <- weights::wtd.hist

    
StartupStats <- fread("data/VentureSource/startupOutcomes.csv")
setnames(StartupStats,"State","startupState")

parentsSpinouts <- fread("data/parentsSpinouts.csv")[,.(gvkey,state,EntityID)]

# Construct flag for spinouts
parentsSpinouts[ , isSpinout := 1]

# Merge with Startup stats
setkey(parentsSpinouts,EntityID)
setkey(StartupStats,EntityID)

StartupStats <- parentsSpinouts[StartupStats]

StartupStats[ is.na(isSpinout), isSpinout := 0]

# Compute counts by industry, for weighting histograms
startupCounts <- StartupStats[ , .N , by = IndustryCodeDesc]
setkey(startupCounts,IndustryCodeDesc)

## Compute fraction of spinouts and non-spinouts that go from non-revenue generating to revenue generating

startupToRevenue <- StartupStats[ , sum(genRevenue) / .N , by = .(IndustryCodeDesc,isSpinout,noRevenue)][ noRevenue == 1][order(IndustryCodeDesc,isSpinout)]
startupToRevenue[ isSpinout == 1, type := "spinout"]
startupToRevenue[ isSpinout == 0, type := "nonSpinout"]
startupToRevenueRatios <- dcast(startupToRevenue, IndustryCodeDesc ~ type, value.var = "V1")
startupToRevenueRatios[ , ratio := spinout / nonSpinout]
setkey(startupToRevenueRatios,IndustryCodeDesc)
startupToRevenueRatios <- startupCounts[startupToRevenueRatios]
wtd.hist(startupToRevenueRatios$ratio , breaks = 100,weight = startupToRevenueRatios$N, xlim = c(0,3))

startupToRevenue_all <- StartupStats[ , sum(genRevenue) / .N , by = .(isSpinout,noRevenue)][ noRevenue == 1]

  
startupToProfitable <- StartupStats[ , sum(profitable) / .N , by = .(IndustryCodeDesc,isSpinout,noRevenue)][ noRevenue == 1][order(IndustryCodeDesc,isSpinout)]
startupToProfitable[ isSpinout == 1, type := "spinout"]
startupToProfitable[ isSpinout == 0, type := "nonSpinout"]
startupToProfitableRatios <- dcast(startupToProfitable, IndustryCodeDesc ~ type, value.var = "V1")
startupToProfitableRatios[ , ratio := spinout / nonSpinout]
setkey(startupToProfitableRatios,IndustryCodeDesc)
startupToProfitableRatios <- startupCounts[startupToProfitableRatios]
wtd.hist(startupToProfitableRatios$ratio , breaks = 100, weight = startupToProfitableRatios$N , xlim = c(0,5))

startupToProfitable_all <- StartupStats[ , sum(profitable) / .N , by = .(isSpinout,noRevenue)][ noRevenue == 1]

revenueToProfitable <- StartupStats[ , sum(profitable) / .N, by = .(IndustryCodeDesc,isSpinout,genRevenue)][ genRevenue == 1][order(IndustryCodeDesc,isSpinout)]
revenueToProfitable[ isSpinout == 1, type := "spinout"]
revenueToProfitable[ isSpinout == 0, type := "nonSpinout"]
revenueToProfitableRatios <- dcast(revenueToProfitable, IndustryCodeDesc ~ type, value.var = "V1")
revenueToProfitableRatios[ , ratio := spinout / nonSpinout]
setkey(revenueToProfitableRatios,IndustryCodeDesc)
revenueToProfitableRatios <- startupCounts[revenueToProfitableRatios]
wtd.hist(revenueToProfitableRatios$ratio , breaks = 100, weight = revenueToProfitableRatios$N, xlim = c(0,5))


allToProfitable <- StartupStats[ , sum(profitable) / .N, by = .(IndustryCodeDesc,isSpinout)]
allToProfitable[ isSpinout == 1, type := "spinout"]
allToProfitable[ isSpinout == 0, type := "nonSpinout"]
allToProfitableRatios <- dcast(allToProfitable, IndustryCodeDesc ~ type, value.var = "V1")
allToProfitableRatios[ , ratio := spinout / nonSpinout]
setkey(allToProfitableRatios,IndustryCodeDesc)
allToProfitableRatios <- startupCounts[allToProfitableRatios]
wtd.hist(allToProfitableRatios$ratio , breaks = 100, weight = allToProfitableRatios$N, xlim = c(0,5))





















bdsData <- fread("raw/bds/bds_f_age_release.csv")
yearStartupsFirms <- bdsData[ , .( allFirms = sum(Firms), startups = Firms[fage4 == "a) 0"]), by = year2]

yearStartupsFirms[ , entryRate := startups / allFirms]

averageEntryRate <- yearStartupsFirms[ year2 >= 1986 & year2 <= 2009, mean(entryRate)]




  

  






